### PR TITLE
Replace mvnrepository.com with search.maven.org

### PR DESCRIPTION
**Pull request by SidB3**

### CODE REVIEW

**Comment by jjohannes** [comment]
Hey, if you do a PR, on whatever topic, on whatever open source repo: please provide context. You put unnecessary burden on maintainers (most of the time maintaining thins in their free time) by just throwing changes at them.

Describe why you do the PR. There is a reason, why there is a description field.

Sorry, but this is not the first time I get something like this. I perceive it as rude.

I'll from now on just close all PRs without any description on repos I maintain.

**Comment by SidB3** [comment]
My apologies @jjohannes. I felt the title described the changes but I can see how that can come off as rude. 

mvnrepository.com is filled with ads and is not an official maven central search website.

search.maven.org is built by the maintainers of Maven Central and does not have any ads. Plus its a much cleaner/nicer experience. 

This PR is just a text replace of mvnrepository.com with search.maven.org

**Comment by jjohannes** [comment]
Thanks for elaborating @SidB3. I used `mvnrepository.com`, although it has a lot of issues, because it has the one quite useful feature that it shows you all the dependencies in a list and lets you navigate between them.

That being said, I have no strong preference here.

So I am happy to accept this change then.

The part of the readme is generated by the build though, you should adjust the URL here:
https://github.com/gradlex-org/java-ecosystem-capabilities/blob/main/gradle/plugins/documentation/src/main/kotlin/gradlexbuild/javaecosystem/capabilities/documentation/ReadmeUpdate.kt#L64

And then run the `:updateReadme` task (which should produce the same thing that you adjusted manually).

**Comment by SidB3** [comment]
Thanks for the clarification @jjohannes. Updated the PR.

**Comment by jjohannes** [comment]
Thank you for the contribution @SidB3!

**Pull request merged**
